description: |
  Extract data from PDF.
executors:
  default:
    description: |
      Basic Docker image
    docker:
    - image: rappdw/docker-java-python
jobs:
  all:
    description: |
      Run python notebook
    executor: default
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "fe:0c:af:21:57:3c:0e:45:f0:e2:fd:48:83:d1:fb:f4"
    - run:
        command: |
          pip install jupyter nbconvert
          git status
          git config user.email "hkkenneth@gmail.com"
          git config user.name "CircleCI Job"
          git config core.autocrlf true
          jupyter nbconvert --execute --to notebook --inplace data-extraction.ipynb
          jupyter nbconvert --execute --to notebook --inplace data-transformation.ipynb
          git add data-extraction.ipynb
          git add data-transformation.ipynb
          git add raw-en.dat
          git add raw-new-en.parquet
          git add raw-old-en.parquet
          git add raw-mode-en.parquet
          git add raw-cluster-en.parquet
          git add transformed-new-en.parquet
          git add transformed-old-en.parquet
          git add transformed-merged-en.parquet
          git commit --allow-empty -am "Automatic commit from CircleCI [skip ci]"
          git push origin master
        name: Git Checkout and run jupyter notebook
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
workflows:
  extraction:
    jobs:
      - all
